language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^php ]]; then phpenv config-rm xdebug.ini; echo "memory_limit=2G" >> /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/travis.ini; fi

script:
  - composer self-update
  - composer update --no-interaction
  - ./vendor/phpunit/phpunit/phpunit -v
